echo "--- Executing initialization force file for gtest.vhd ---"

echo "Setting clock period to 50 ns, starting at 50 ns."
force /clk 0  0
force /clk 0 25 -r 50
force /clk 1 50 -r 50

echo "Resetting processor for 5 ns."
force /reset_l 0 @0
force /reset_l 1 @5

-- echo "Initializing the processor."
-- force /start_h 0 @0
-- force /start_h 1 @10

-- Test case: lowering start_h should not impact the function of the processor
-- force /start_h 0 @ 100

echo "Done initializing processor, loading gtest.vhd program code."
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(0) X"1A"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(1) X"6A"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(2) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(3) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(4) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(5) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(6) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(7) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(8) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(9) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(10) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(11) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(12) X"1D"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(13) X"7A"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(14) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(15) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(16) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(17) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(18) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(19) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(20) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(21) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(22) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(23) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(24) X"1D"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(25) X"6C"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(26) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(27) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(28) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(29) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(30) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(31) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(32) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(33) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(34) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(35) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(36) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(37) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(38) X"F9"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(39) X"0F"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(40) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(41) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(42) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(43) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(44) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(45) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(46) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(47) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(48) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(49) X"00"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(50) X"DD"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(51) X"BA"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(52) X"0D"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(53) X"60"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(54) X"AD"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(55) X"BB"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(56) X"AD"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(57) X"BB"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(58) X"DD"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(59) X"BA"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(60) X"AD"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(61) X"BB"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(62) X"AD"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(63) X"BB"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(64) X"AD"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(65) X"BB"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(66) X"AD"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(67) X"BB"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(68) X"AD"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(69) X"BB"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(70) X"AD"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(71) X"BB"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(72) X"AD"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(73) X"BB"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(74) X"AD"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(75) X"BB"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(76) X"AD"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(77) X"BB"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(78) X"AD"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(79) X"BB"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(80) X"AD"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(81) X"BB"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(82) X"AD"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(83) X"BB"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(84) X"AD"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(85) X"BB"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(86) X"AD"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(87) X"BB"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(88) X"AD"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(89) X"BB"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(90) X"AD"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(91) X"BB"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(92) X"AD"
change /mp3_cpu/DRAM_magic/vhdl_memory/mem(93) X"BB"
run 5
echo "Done loading gtest.vhd program code."
