echo "--- Executing initialization force file for teststd.vhd ---"

echo "Setting clock period to 34 ns, starting at 34 ns."
force /clk 1  0
force /clk 0 17 -r 34
force /clk 1 34 -r 34

echo "Resetting processor for 5 ns."
force /reset_l 0 @0
force /reset_l 1 @5

-- echo "Initializing the processor."
-- force /start_h 0 @0
-- force /start_h 1 @10

-- Test case: lowering start_h should not impact the function of the processor
-- force /start_h 0 @ 100

echo "Done initializing processor, loading teststd.vhd program code."
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(0) X"2F"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(1) X"19"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(2) X"67"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(3) X"1B"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(4) X"AB"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(5) X"1D"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(6) X"14"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(7) X"62"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(8) X"15"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(9) X"64"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(10) X"16"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(11) X"66"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(12) X"40"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(13) X"6E"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(14) X"41"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(15) X"7A"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(16) X"80"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(17) X"6E"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(18) X"84"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(19) X"7A"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(20) X"40"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(21) X"6E"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(22) X"C1"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(23) X"7C"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(24) X"81"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(25) X"6E"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(26) X"C5"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(27) X"7C"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(28) X"82"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(29) X"6E"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(30) X"47"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(31) X"78"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(32) X"84"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(33) X"68"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(34) X"47"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(35) X"68"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(36) X"43"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(37) X"3A"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(38) X"FF"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(39) X"0F"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(40) X"40"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(41) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(42) X"C0"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(43) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(44) X"40"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(45) X"01"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(46) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(47) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(48) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(49) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(50) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(51) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(64) X"11"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(65) X"11"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(66) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(67) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(68) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(69) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(70) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(71) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(72) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(73) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(74) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(75) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(76) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(77) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(78) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(79) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(192) X"22"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(193) X"22"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(194) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(195) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(196) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(197) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(198) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(199) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(200) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(201) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(202) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(203) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(204) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(205) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(206) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(207) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(320) X"33"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(321) X"33"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(322) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(323) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(324) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(325) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(326) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(327) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(328) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(329) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(330) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(331) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(332) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(333) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(334) X"00"
change /mp3_cpu/memory/DRAM/vhdl_memory/mem(335) X"00"
run 5
echo "Done loading teststd.vhd program code."
