-- VHDL Entity ece411.BigWay.symbol
--
-- Created:
--          by - rchoxi2.stdt (eelnx36.ews.illinois.edu)
--          at - 23:40:56 11/30/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY BigWay IS
   PORT( 
      DataWrite      : IN     std_logic;
      Datain         : IN     lc3b_oword;
      DirtyIn        : IN     std_logic;
      DirtyWrite     : IN     std_logic;
      RESET_L        : IN     std_logic;
      TagIn          : IN     lc3b_tag;
      index          : IN     lc3b_cindex;
      offset         : IN     lc3b_coffset;
      Dirty          : OUT    std_logic;
      LineOut        : OUT    lc3b_oword;
      joined_address : OUT    lc3b_word;
      prehit         : OUT    std_logic;
      waydata        : OUT    lc3b_word
   );

-- Declarations

END BigWay ;

--
-- VHDL Architecture ece411.BigWay.struct
--
-- Created:
--          by - rchoxi2.stdt (eelnx36.ews.illinois.edu)
--          at - 23:40:56 11/30/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF BigWay IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL TagOut    : lc3b_tag;
   SIGNAL Valid     : std_logic;
   SIGNAL tag_equal : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL LineOut_internal : lc3b_oword;


   -- Component Declarations
   COMPONENT WAY
   PORT (
      DataWrite  : IN     std_logic ;
      Datain     : IN     lc3b_oword ;
      DirtyIn    : IN     std_logic ;
      DirtyWrite : IN     std_logic ;
      RESET_L    : IN     std_logic ;
      TagIn      : IN     lc3b_tag ;
      index      : IN     lc3b_cindex ;
      Data       : OUT    lc3b_oword ;
      Dirty      : OUT    std_logic ;
      Tag        : OUT    lc3b_tag ;
      Valid      : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT addr_joiner
   PORT (
      index   : IN     lc3b_cindex ;
      offset  : IN     lc3b_coffset ;
      tag     : IN     lc3b_tag ;
      address : OUT    lc3b_word 
   );
   END COMPONENT;
   COMPONENT and2
   PORT (
      a : IN     std_logic ;
      b : IN     std_logic ;
      s : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT tag_comp
   PORT (
      tag_addr  : IN     lc3b_tag ;
      tag_cache : IN     lc3b_tag ;
      equal     : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT wordmux_c
   PORT (
      databig : IN     lc3b_oword ;
      offset  : IN     lc3b_coffset ;
      waydata : OUT    lc3b_word 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : WAY USE ENTITY ece411.WAY;
   FOR ALL : addr_joiner USE ENTITY ece411.addr_joiner;
   FOR ALL : and2 USE ENTITY ece411.and2;
   FOR ALL : tag_comp USE ENTITY ece411.tag_comp;
   FOR ALL : wordmux_c USE ENTITY ece411.wordmux_c;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   WAY0 : WAY
      PORT MAP (
         DataWrite  => DataWrite,
         Datain     => Datain,
         DirtyIn    => DirtyIn,
         DirtyWrite => DirtyWrite,
         RESET_L    => RESET_L,
         TagIn      => TagIn,
         index      => index,
         Data       => LineOut_internal,
         Dirty      => Dirty,
         Tag        => TagOut,
         Valid      => Valid
      );
   aAddrJoiner : addr_joiner
      PORT MAP (
         index   => index,
         offset  => offset,
         tag     => TagOut,
         address => joined_address
      );
   andprehit : and2
      PORT MAP (
         a => tag_equal,
         b => Valid,
         s => prehit
      );
   comp0 : tag_comp
      PORT MAP (
         tag_addr  => TagIn,
         tag_cache => TagOut,
         equal     => tag_equal
      );
   wmux0 : wordmux_c
      PORT MAP (
         databig => LineOut_internal,
         offset  => offset,
         waydata => waydata
      );

   -- Implicit buffered output assignments
   LineOut <= LineOut_internal;

END struct;
