-- VHDL Entity ece411.EX_STAGE.interface
--
-- Created:
--          by - cjpark3.stdt (eelnx24.ews.illinois.edu)
--          at - 23:40:06 10/20/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY EX_STAGE IS
   PORT( 
      ALUop_EX        : IN     LC3b_ALUop;
      AdjSel_EX       : IN     std_logic;
      BaseSel_EX      : IN     std_logic;
      ImmSel_EX       : IN     std_logic;
      PC_EX           : IN     lc3b_word;
      SR1_data_EX     : IN     lc3b_word;
      SR2_data_EX     : IN     lc3b_word;
      SextSel_EX      : IN     std_logic;
      adj_imm5_EX     : IN     lc3b_word;
      adj_offset6_EX  : IN     lc3b_word;
      adj_offset9_EX  : IN     lc3b_word;
      sext_offset6_EX : IN     lc3b_word;
      ALUout_EX       : OUT    lc3b_word;
      address_EX      : OUT    lc3b_word
   );

-- Declarations

END EX_STAGE ;

--
-- VHDL Architecture ece411.EX_STAGE.struct
--
-- Created:
--          by - cjpark3.stdt (eelnx24.ews.illinois.edu)
--          at - 23:40:06 10/20/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF EX_STAGE IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL baseMuxout    : LC3b_word;
   SIGNAL immMuxout     : LC3b_word;
   SIGNAL offset6Muxout : LC3b_word;
   SIGNAL offsetMuxout  : LC3b_word;


   -- Component Declarations
   COMPONENT ALU
   PORT (
      A      : IN     LC3b_word ;
      ALUop  : IN     LC3b_aluop ;
      B      : IN     LC3b_word ;
      ALUout : OUT    LC3b_word 
   );
   END COMPONENT;
   COMPONENT Adder
   PORT (
      A : IN     lc3b_word ;
      B : IN     lc3b_word ;
      F : OUT    lc3b_word 
   );
   END COMPONENT;
   COMPONENT WordMux2
   PORT (
      A   : IN     LC3b_word ;
      B   : IN     LC3b_word ;
      Sel : IN     std_logic ;
      F   : OUT    LC3b_word 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : ALU USE ENTITY ece411.ALU;
   FOR ALL : Adder USE ENTITY ece411.Adder;
   FOR ALL : WordMux2 USE ENTITY ece411.WordMux2;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   aALU : ALU
      PORT MAP (
         A      => SR1_data_EX,
         ALUop  => ALUop_EX,
         B      => immMuxout,
         ALUout => ALUout_EX
      );
   aAdder : Adder
      PORT MAP (
         A => offsetMuxout,
         B => baseMuxout,
         F => address_EX
      );
   adjmux : WordMux2
      PORT MAP (
         A   => sext_offset6_EX,
         B   => adj_offset6_EX,
         Sel => AdjSel_EX,
         F   => offset6Muxout
      );
   basemux : WordMux2
      PORT MAP (
         A   => SR1_data_EX,
         B   => PC_EX,
         Sel => BaseSel_EX,
         F   => baseMuxout
      );
   immMux : WordMux2
      PORT MAP (
         A   => SR2_data_EX,
         B   => adj_imm5_EX,
         Sel => ImmSel_EX,
         F   => immMuxout
      );
   sextmux : WordMux2
      PORT MAP (
         A   => offset6Muxout,
         B   => adj_offset9_EX,
         Sel => SextSel_EX,
         F   => offsetMuxout
      );

END struct;
