-- VHDL Entity ece411.ID_STAGE.interface
--
-- Created:
--          by - rchoxi2.stdt (gllnx7.ews.illinois.edu)
--          at - 23:05:08 11/08/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY ID_STAGE IS
   PORT( 
      DR              : IN     lc3b_reg;
      DestReg         : IN     lc3b_reg;
      RESET_L         : IN     std_logic;
      RegWrite        : IN     std_logic;
      SR1             : IN     lc3b_reg;
      SR2             : IN     lc3b_reg;
      WriteData       : IN     lc3b_word;
      imm5            : IN     lc3b_imm5;
      offset6         : IN     lc3b_index6;
      offset9         : IN     lc3b_offset9;
      SR1_data_ID     : OUT    lc3b_word;
      SR2_data_ID     : OUT    lc3b_word;
      STR_data_ID     : OUT    lc3b_word;
      adj_offset6_ID  : OUT    lc3b_word;
      adj_offset9_ID  : OUT    lc3b_word;
      sext_imm5_ID    : OUT    lc3b_word;
      sext_offset6_ID : OUT    lc3b_word
   );

-- Declarations

END ID_STAGE ;

--
-- VHDL Architecture ece411.ID_STAGE.struct
--
-- Created:
--          by - rchoxi2.stdt (gllnx7.ews.illinois.edu)
--          at - 23:05:08 11/08/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF ID_STAGE IS

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   COMPONENT ADJ6
   PORT (
      index6  : IN     LC3b_index6 ;
      ADJ6out : OUT    LC3b_word 
   );
   END COMPONENT;
   COMPONENT ADJ9
   PORT (
      offset9 : IN     LC3b_offset9 ;
      ADJ9out : OUT    LC3b_word 
   );
   END COMPONENT;
   COMPONENT RegFile
   PORT (
      DR       : IN     LC3b_reg ;
      DEST     : IN     LC3b_reg ;
      DataIn   : IN     LC3b_word ;
      RESET_L  : IN     std_logic ;
      RegWrite : IN     std_logic ;
      SrcA     : IN     LC3b_reg ;
      SrcB     : IN     LC3b_reg ;
      --clk      : IN     std_logic;
      RFAout   : OUT    LC3b_word ;
      RFBout   : OUT    LC3b_word ;
      RFDout   : OUT    LC3b_word 
   );
   END COMPONENT;
   COMPONENT SEXT5
   PORT (
      imm5    : IN     LC3b_imm5 ;
      imm5ext : OUT    LC3b_word 
   );
   END COMPONENT;
   COMPONENT SEXT6
   PORT (
      imm6    : IN     LC3b_index6 ;
      imm6ext : OUT    LC3b_word 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : ADJ6 USE ENTITY ece411.ADJ6;
   FOR ALL : ADJ9 USE ENTITY ece411.ADJ9;
   FOR ALL : RegFile USE ENTITY ece411.RegFile;
   FOR ALL : SEXT5 USE ENTITY ece411.SEXT5;
   FOR ALL : SEXT6 USE ENTITY ece411.SEXT6;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   aADJ6 : ADJ6
      PORT MAP (
         index6  => offset6,
         ADJ6out => adj_offset6_ID
      );
   aADJ9 : ADJ9
      PORT MAP (
         offset9 => offset9,
         ADJ9out => adj_offset9_ID
      );
   aRegFile : RegFile
      PORT MAP (
         DR       => DR,
         DEST     => DestReg,
         DataIn   => WriteData,
         RESET_L  => RESET_L,
         RegWrite => RegWrite,
         SrcA     => SR1,
         SrcB     => SR2,
         RFAout   => SR1_data_ID,
         RFBout   => SR2_data_ID,
         RFDout   => STR_data_ID
      );
   aSEXT5 : SEXT5
      PORT MAP (
         imm5    => imm5,
         imm5ext => sext_imm5_ID
      );
   aSEXT6 : SEXT6
      PORT MAP (
         imm6    => offset6,
         imm6ext => sext_offset6_ID
      );

END struct;
