-- VHDL Entity ece411.IF_STAGE.interface
--
-- Created:
--          by - tkalbar2.stdt (gllnx16.ews.illinois.edu)
--          at - 07:23:58 11/12/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY IF_STAGE IS
   PORT( 
      ALUout_EX   : IN     lc3b_word;
      Instrin     : IN     lc3b_word;
      RESET_L     : IN     std_logic;
      ZextSel_WB  : IN     std_logic;
      address_MEM : IN     lc3b_word;
      brSel       : IN     std_logic;
      clk         : IN     std_logic;
      dataout_WB  : IN     lc3b_word;
      fetch       : IN     std_logic;
      jump_EX     : IN     std_logic;
      Instrout    : OUT    lc3b_word;
      Opcode_IF   : OUT    lc3b_opcode;
      PC_IF       : OUT    lc3b_word;
      PCout       : OUT    lc3b_word
   );

-- Declarations

END IF_STAGE ;

--
-- VHDL Architecture ece411.IF_STAGE.struct
--
-- Created:
--          by - tkalbar2.stdt (gllnx16.ews.illinois.edu)
--          at - 07:23:58 11/12/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF IF_STAGE IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL F    : LC3b_word;
   SIGNAL F1   : LC3b_word;
   SIGNAL F2   : LC3b_word;
   SIGNAL NOP  : LC3b_word;
   SIGNAL Zero : std_logic;
   SIGNAL s    : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL PC_IF_internal : lc3b_word;
   SIGNAL PCout_internal : lc3b_word;


   -- Component Declarations
   COMPONENT Plus2
   PORT (
      PCout      : IN     LC3b_word ;
      PCPlus2out : OUT    LC3b_word 
   );
   END COMPONENT;
   COMPONENT Reg16
   PORT (
      Input  : IN     LC3b_word ;
      RESET  : IN     std_logic ;
      clk    : IN     std_logic ;
      load   : IN     std_logic ;
      Output : OUT    LC3b_word 
   );
   END COMPONENT;
   COMPONENT WordMux2
   PORT (
      A   : IN     LC3b_word ;
      B   : IN     LC3b_word ;
      Sel : IN     std_logic ;
      F   : OUT    LC3b_word 
   );
   END COMPONENT;
   COMPONENT or4
   PORT (
      A : IN     std_logic ;
      B : IN     std_logic ;
      C : IN     std_logic ;
      D : IN     std_logic ;
      F : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Plus2 USE ENTITY ece411.Plus2;
   FOR ALL : Reg16 USE ENTITY ece411.Reg16;
   FOR ALL : WordMux2 USE ENTITY ece411.WordMux2;
   FOR ALL : or4 USE ENTITY ece411.or4;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 2 Instr
   NOP <= "0000000000000000";
   Opcode_IF <= Instrin(15 DOWNTO 12);
   Zero <= '0';
                                     


   -- Instance port mappings.
   PCPlus2 : Plus2
      PORT MAP (
         PCout      => PCout_internal,
         PCPlus2out => PC_IF_internal
      );
   PC : Reg16
      PORT MAP (
         Input  => F2,
         RESET  => RESET_L,
         clk    => clk,
         load   => fetch,
         Output => PCout_internal
      );
   FlushMux : WordMux2
      PORT MAP (
         A   => Instrin,
         B   => NOP,
         Sel => s,
         F   => Instrout
      );
   brMux : WordMux2
      PORT MAP (
         A   => F,
         B   => address_MEM,
         Sel => brSel,
         F   => F1
      );
   jmpMux : WordMux2
      PORT MAP (
         A   => PC_IF_internal,
         B   => ALUout_EX,
         Sel => jump_EX,
         F   => F
      );
   trapMux2 : WordMux2
      PORT MAP (
         A   => F1,
         B   => dataout_WB,
         Sel => ZextSel_WB,
         F   => F2
      );
   U_0 : or4
      PORT MAP (
         A => brSel,
         B => jump_EX,
         C => ZextSel_WB,
         D => Zero,
         F => s
      );

   -- Implicit buffered output assignments
   PC_IF <= PC_IF_internal;
   PCout <= PCout_internal;

END struct;
