-- VHDL Entity ece411.L2_Controller.symbol
--
-- Created:
--          by - rchoxi2.stdt (gllnx14.ews.illinois.edu)
--          at - 04:06:18 12/02/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY L2_Controller IS
   PORT( 
      RESET_L      : IN     std_logic;
      all_access   : IN     std_logic;
      clk          : IN     std_logic;
      dirty        : IN     std_logic;
      hit          : IN     std_logic;
      miss         : IN     std_logic;
      pmresp_h     : IN     std_logic;
      PMREAD_L     : OUT    std_logic;
      PMWRITE_L    : OUT    std_logic;
      in_idlehit   : OUT    std_logic;
      in_load      : OUT    std_logic;
      in_writeback : OUT    std_logic
   );

-- Declarations

END L2_Controller ;

--
-- VHDL Architecture ece411.L2_Controller.fsm
--
-- Created:
--          by - rchoxi2.stdt (gllnx14.ews.illinois.edu)
--          at - 04:06:18 12/02/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;
 
ARCHITECTURE fsm OF L2_Controller IS

   TYPE STATE_TYPE IS (
      pending,
      idlehit,
      write_back,
      load
   );
 
   -- State vector declaration
   ATTRIBUTE state_vector : string;
   ATTRIBUTE state_vector OF fsm : ARCHITECTURE IS "current_state";

   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      clk,
      RESET_L
   )
   -----------------------------------------------------------------
   BEGIN
      IF (RESET_L = '0') THEN
         current_state <= pending;
      ELSIF (clk'EVENT AND clk = '1') THEN
         current_state <= next_state;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      all_access,
      current_state,
      dirty,
      hit,
      miss,
      pmresp_h
   )
   -----------------------------------------------------------------
   BEGIN
      CASE current_state IS
         WHEN pending => 
            IF (all_access = '1') THEN 
               next_state <= idlehit;
            ELSE
               next_state <= pending;
            END IF;
         WHEN idlehit => 
            IF (miss = '1' AND
                dirty = '0') THEN 
               next_state <= load;
            ELSIF (miss = '1' AND
                   dirty = '1') THEN 
               next_state <= write_back;
            ELSIF (hit = '1') THEN 
               next_state <= pending;
            ELSE
               next_state <= idlehit;
            END IF;
         WHEN write_back => 
            IF (pmresp_h = '1') THEN 
               next_state <= load;
            ELSE
               next_state <= write_back;
            END IF;
         WHEN load => 
            IF (pmresp_h = '1') THEN 
               next_state <= pending;
            ELSE
               next_state <= load;
            END IF;
         WHEN OTHERS =>
            next_state <= pending;
      END CASE;
   END PROCESS nextstate_proc;
 
   -----------------------------------------------------------------
   output_proc : PROCESS ( 
      current_state
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default Assignment
      PMREAD_L <= '1';
      PMWRITE_L <= '1';
      in_idlehit <= '0';
      in_load <= '0';
      in_writeback <= '0';

      -- Combined Actions
      CASE current_state IS
         WHEN idlehit => 
            in_idlehit <= '1';
         WHEN write_back => 
            pmwrite_l <= '0' after 3ns;
            in_writeback <= '1';
            in_idlehit <= '0';
         WHEN load => 
            pmread_l <= '0' after 3ns;
            in_load <= '1';
            in_idlehit <= '0';
         WHEN OTHERS =>
            NULL;
      END CASE;
   END PROCESS output_proc;
 
END fsm;
