-- VHDL Entity ece411.Memory3.symbol
--
-- Created:
--          by - rchoxi2.stdt (eelnx28.ews.illinois.edu)
--          at - 23:31:50 10/25/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY Memory3 IS
   PORT( 
      D_ADDRESS  : IN     LC3b_word;
      D_DATAIN   : IN     LC3b_word;
      D_MREAD_L  : IN     std_logic;
      D_MWRITE_L : IN     std_logic;
      I_ADDRESS  : IN     LC3b_word;
      I_MREAD_L  : IN     std_logic;
      RESET_L    : IN     std_logic;
      D_DATAOUT  : OUT    LC3b_word;
      D_MRESP_H  : OUT    std_logic;
      I_DATAOUT  : OUT    LC3b_word;
      I_MRESP_H  : OUT    std_logic
   );

-- Declarations

END Memory3 ;

--
-- VHDL Architecture ece411.Memory3.struct
--
-- Created:
--          by - rchoxi2.stdt (eelnx28.ews.illinois.edu)
--          at - 23:31:50 10/25/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF Memory3 IS

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   COMPONENT MagicMemory
   PORT (
      D_ADDRESS  : IN     LC3b_word ;
      D_DATAIN   : IN     LC3b_word ;
      D_MREAD_L  : IN     std_logic ;
      D_MWRITE_L : IN     std_logic ;
      I_ADDRESS  : IN     LC3b_word ;
      I_MREAD_L  : IN     std_logic ;
      RESET_L    : IN     std_logic ;
      D_DATAOUT  : OUT    LC3b_word ;
      D_MRESP_H  : OUT    std_logic ;
      I_DATAOUT  : OUT    LC3b_word ;
      I_MRESP_H  : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : MagicMemory USE ENTITY ece411.MagicMemory;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   DRAM_magic : MagicMemory
      PORT MAP (
         D_ADDRESS  => D_ADDRESS,
         D_DATAIN   => D_DATAIN,
         D_MREAD_L  => D_MREAD_L,
         D_MWRITE_L => D_MWRITE_L,
         I_ADDRESS  => I_ADDRESS,
         I_MREAD_L  => I_MREAD_L,
         RESET_L    => RESET_L,
         D_DATAOUT  => D_DATAOUT,
         D_MRESP_H  => D_MRESP_H,
         I_DATAOUT  => I_DATAOUT,
         I_MRESP_H  => I_MRESP_H
      );

END struct;
