-- VHDL Entity ece411.Memory.generatedInstance
--
-- Created:
--          by - tkalbar2.stdt (eelnx13.ews.illinois.edu)
--          at - 23:14:33 09/01/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY Memory IS
   PORT( 
      MWRITEL_L : IN     std_logic;
      MWRITEH_L : IN     std_logic;
      MREAD_L   : IN     std_logic;
      MRESP_H   : OUT    std_logic;
      RESET_L   : IN     std_logic;
      DATAOUT   : IN     LC3b_word;
      ADDRESS   : IN     LC3b_word;
      DATAIN    : OUT    LC3b_word;
      clk       : IN     std_logic
   );

END Memory ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF Memory IS 
BEGIN


END generatedInstance;
