-- VHDL Entity ece411.StallUnit.interface
--
-- Created:
--          by - rchoxi2.stdt (gllnx7.ews.illinois.edu)
--          at - 00:21:32 11/09/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY StallUnit IS
   PORT( 
      D_MREAD_L   : IN     std_logic;
      D_MRESP_H   : IN     std_logic;
      D_MWRITE_L  : IN     std_logic;
      I_MRESP_H   : IN     std_logic;
      Read_EX     : IN     std_logic;
      RegWrite_ID : IN     std_logic;
      mem_stall   : OUT    std_logic
   );

-- Declarations

END StallUnit ;

--
-- VHDL Architecture ece411.StallUnit.struct
--
-- Created:
--          by - rchoxi2.stdt (gllnx7.ews.illinois.edu)
--          at - 00:21:32 11/09/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF StallUnit IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL not_access : std_logic;
   SIGNAL s          : std_logic;


   -- Component Declarations
   COMPONENT and2
   PORT (
      a : IN     std_logic ;
      b : IN     std_logic ;
      s : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT or2
   PORT (
      a : IN     std_logic ;
      b : IN     std_logic ;
      s : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : and2 USE ENTITY ece411.and2;
   FOR ALL : or2 USE ENTITY ece411.or2;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : and2
      PORT MAP (
         a => I_MRESP_H,
         b => s,
         s => mem_stall
      );
   U_1 : and2
      PORT MAP (
         a => D_MREAD_L,
         b => D_MWRITE_L,
         s => not_access
      );
   U_2 : or2
      PORT MAP (
         a => D_MRESP_H,
         b => not_access,
         s => s
      );

END struct;
