-- VHDL Entity ece411.WAY.symbol
--
-- Created:
--          by - tkalbar2.ece411_G2 (eelnx34.ews.illinois.edu)
--          at - 23:54:28 10/19/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY WAY IS
   PORT( 
      DataWrite  : IN     std_logic;
      Datain     : IN     lc3b_oword;
      DirtyIn    : IN     std_logic;
      DirtyWrite : IN     std_logic;
      RESET_L    : IN     std_logic;
      TagIn      : IN     lc3b_tag;
      index      : IN     lc3b_cindex;
      Data       : OUT    lc3b_oword;
      Dirty      : OUT    std_logic;
      Tag        : OUT    lc3b_tag;
      Valid      : OUT    std_logic
   );

-- Declarations

END WAY ;

--
-- VHDL Architecture ece411.WAY.struct
--
-- Created:
--          by - tkalbar2.ece411_G2 (eelnx34.ews.illinois.edu)
--          at - 23:54:28 10/19/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF WAY IS

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   COMPONENT DataArray
   PORT (
      RESET_L   : IN     std_logic ;
      DataWrite : IN     std_logic ;
      Index     : IN     LC3b_cindex ;
      DataIn    : IN     LC3b_oword ;
      DataOut   : OUT    LC3b_oword 
   );
   END COMPONENT;
   COMPONENT DirtyArray
   PORT (
      DirtyIn    : IN     std_logic ;
      DirtyWrite : IN     std_logic ;
      Reset_l    : IN     std_logic ;
      index      : IN     lc3b_cindex ;
      DirtyOut   : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT TagArray
   PORT (
      Reset_l  : IN     std_logic ;
      TagIn    : IN     lc3b_tag ;
      TagWrite : IN     std_logic ;
      index    : IN     lc3b_cindex ;
      Tagout   : OUT    lc3b_tag 
   );
   END COMPONENT;
   COMPONENT Valid_Array
   PORT (
      Reset_l    : IN     std_logic ;
      ValidWrite : IN     std_logic ;
      index      : IN     lc3b_cindex ;
      ValidOut   : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : DataArray USE ENTITY ece411.DataArray;
   FOR ALL : DirtyArray USE ENTITY ece411.DirtyArray;
   FOR ALL : TagArray USE ENTITY ece411.TagArray;
   FOR ALL : Valid_Array USE ENTITY ece411.Valid_Array;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : DataArray
      PORT MAP (
         RESET_L   => RESET_L,
         DataWrite => DataWrite,
         Index     => index,
         DataIn    => Datain,
         DataOut   => Data
      );
   U_1 : DirtyArray
      PORT MAP (
         DirtyIn    => DirtyIn,
         DirtyWrite => DirtyWrite,
         Reset_l    => RESET_L,
         index      => index,
         DirtyOut   => Dirty
      );
   U_3 : TagArray
      PORT MAP (
         Reset_l  => RESET_L,
         TagIn    => TagIn,
         TagWrite => DataWrite,
         index    => index,
         Tagout   => Tag
      );
   U_2 : Valid_Array
      PORT MAP (
         Reset_l    => RESET_L,
         ValidWrite => DataWrite,
         index      => index,
         ValidOut   => Valid
      );

END struct;
